### ISSUE TITLE
feat: add a FAQ for Web3Task

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-org#20]
Prepare questions and answers for Web3Task FAQ on the LP.
Use the same model as described below:
![Image](https://github.com/w3b3d3v/web3task-org/assets/90667119/51638a07-f6be-4331-b48d-c2e5e16f3c04)

Please do not hesitate to ask your questions, they will probably become the FAQ itself 😆 , so as the answers! I will personally help on this one.

**Comment by viniblack** [comment]
lets go

**Comment by 0xneves** [comment]
Please @viniblack, translate to english and add here the results

**Comment by viniblack** [comment]
1. **What is Web3Task?**
Web3Task is an innovative platform that solves the challenge of monetizing contributions by fragmenting tasks in a way inspired by the GitHub issue model. Our focus is to reduce the barriers to entry that students face in the job market by providing opportunities to gain real work experience.

2. **How does it work?**
We connect workers to projects, eliminating high partner fees and the lack of skills assessment. Our protocol empowers users through active participation in real projects, allowing recruiters to find professionals with certified experience. We provide tools like scoring to measure results by tokenizing work, social profiles, and portfolios. A network to facilitate connections between users and projects, to create a transparent and trustworthy Web 3.0 environment.

3. **What are the benefits of joining Web3Task as a student?**
You will have the opportunity to gain hands-on experience working on real projects, allowing you to build a robust and verifiable portfolio in the chain, as well as expanding your professional network and the opportunity to be hired by Kyodo.

4. **Who can complete a task?**
Anyone who can deliver what is asked for can participate. However, our platform is mainly focused on students and offers them advantages over freelancers due to our bidding system, thus prioritizing the inclusion and professional growth of students.
The recruiter can choose from the list of interested parties - after analyzing their social profiles, GitHub, LinkedIn - who is best suited to perform the task.

5. **Who can create a task?**
Only platform administrators can create tasks for their interests, while recruiters, who are KYC-authenticated entities, can create tasks.

6. **Is there a ranking of users?**
We have implemented a gamification system for recruiters and contributors. Through our Access Control V2 technology, users increase their score by delivering or creating tasks efficiently and on time. This score is used to rank users on the platform, which increases reliability. However, in case of problems, it is possible to open a dispute.

7. **How do the disputes work?**
Instead of a traditional dispute system, we have chosen a gamified approach. Initiating a dispute is considered risky for both parties, as a dispute drastically lowers the DAO's score for the party whose decision was unfavorable. This policy encourages collaborative problem-solving, which avoids unnecessary disputes and serious harm to those who are wrong. This is why it is so important to describe the desired task correctly and also to perform the chosen task with finesse.

8. **What are the benefits of participating in Web3Task as a recruiter?**
You will be able to find people who can meet your needs, often at a lower cost than expanding your internal team or finding a freelancer.

9. **What types of tasks are available on the platform?**
You'll find a wide range of development tasks available. From programming tasks to design, planning, and other areas of development.

**Comment by 0xneves** [comment]
Issue was solved
